---
- name: block public use of C drive [block-c-drive-user.yml]
  hosts: public
  serial: 1
  gather_facts: no
  become_method: runas
  become: yes
  become_user: all
  tasks:
  - name: verify current user
    win_command: whoami
    register: currUser

  - debug: var=currUser

  - name: Add explorer policy
    win_regedit:
      path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
      state: present

  - name: Add or update registry path to block All public user access to c drive 
    win_regedit:
      path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
      name: NoViewOnDrive
      data: 4
      type: dword
      state: absent
