- import_playbook: remove-user.yml
- import_playbook: config-local-machine.yml
- import_playbook: onedrive.yml
- import_playbook: install-7zip.yml
- import_playbook: install-chrome.yml
- import_playbook: install-firefox.yml
- import_playbook: setup-all-user-admPriv.yml
