---
- name: install chrome with chocolatey
  gather_facts: no
  hosts: all
  tasks:
    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        state: present
      ignore_errors: yes
