---
- hosts: public
  tasks: 
#    - name: make sure BAPLAdmin (nonstandard) is gone
#      win_user:
#        name: BAPLAdmin
#        state: absent

    - name: Ensure public access user is gone
      win_user:
         name: All
         state: absent
