---
- name: Remove people icon from taskbar
- hosts: public
  become_method: runas
  become_user: all
  become:
  gather_facts: no

  - name: Add explorer policy to the path
    win_regedit:
      path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
      state: present

  - name: Add or update HidePeopleBar
    win_regedit:
      path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"
      name: HidePeopleBar
      data: 1
      type: dword
      state: present

