---
- name: Remove people icon from taskbar
  hosts: public
  become_method: runas
  become_user: all
  become: yes
  gather_facts: no
  tasks:

  - name: Add or update PeopleBand
    win_regedit:
      path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\People"
      name: PeopleBand
      data: 0
      type: dword
      state: present

