---
- name: create All user with elevated privs
  hosts: public
  gather_facts: no
  tasks: 

    - name: Ensure public access user is present
      win_user:
         name: All
         password: password
         state: present
         user_cannot_change_password: yes
         groups:
            - Users, Administrators
         group_action: replace

#    - name: Check user
#      become: yes
#      become_user: all
#      become_method: runas
#      win_command: gpresult /r
#      register: userInfo
#    - debug: var=userInfo 
