- hosts: public
  tasks:

  - name: check login as All user
    become_method: runas
    become: yes
    become_user: all
    become_flags: logon_flags=with_profile
    win_command: whoami
    register: outStuff2

  - debug: var=outStuff2
 
  - name: Remove all Appx packages for user all
    become_method: runas
    become: yes
    become_user: all
    become_flags: logon_flags=with_profile    
    win_shell: |
      Get-AppxPackage | Remove-AppxPackage
    register: appx
    changed_when: "'Deployment operation progress: ' in appx.stderr"
    failed_when: no
    tags: appx

  - name: Remove all Appx provisioned packages
    become_method: runas
    become: yes
    become_user: all
    become_flags: logon_flags=with_profile
    win_shell: |
      Get-AppxProvisionedPackage -Online | Remove-AppxProvisionedPackage -Online
    register: appx
#    changed_when: "'Deployment operation progress: ' in appx.stderr"
    failed_when: no
    tags: appx
