---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: public
  gather_facts: false
  tasks:
    # Search-only, return list of found updates (if any), log to c:\ansible_wu.txt
    - name: Search updates
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        state: searched
        log_path: c:\ansible_wu.txt
      register: result

    # reboot only if required may have already staged the update and we just need a reboot
    - win_reboot:
      pre_reboot_delay: 60
      msg: Windows needs to reboot to apply updates. Rebooting in 60 seconds.
      when: result.reboot_required

    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    # output results
    - debug: var=result
    
    # reboot only if required
    - win_reboot:
      pre_reboot_delay: 60
      msg: Windows needs to reboot to apply updates. Rebooting in 60 seconds.
      when: result.reboot_requireda

